### ISSUE TITLE
Make code coverage above 90% on TopoEmbedX (because of JMLR requirements)

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/TopoEmbedX#19]
# What?

JMLR requires that unit-tests' code coverage is "close to 100%". See: https://www.jmlr.org/mloss/mloss-info.html

We can see that, currently, it is at 85%.

![Screen Shot 2023-09-19 at 10 22 22 AM](https://github.com/pyt-team/TopoEmbedX/assets/8267869/96088d2d-25f7-4188-92a2-c2eca06fbd55)

We should make it >90%.

# How?

Go to the code coverage page for TopoEmbedX and observe which lines of code are not tested. Write tests for them.
https://app.codecov.io/gh/pyt-team/TopoEmbedX

**Comment by ninamiolane** [comment]
@devendragovil any chance you could help with this? Thanks in advance.

**Comment by mhajij** [comment]
@maneelusf @gurug-dev

**Comment by devendragovil** [comment]
Yes I will get working on this @ninamiolane

**Comment by devendragovil** [comment]
The test coverage has increased to >90% after the recent PR.

**Comment by ninamiolane** [comment]
Excellent! Thanks @devendragovil
