### ISSUE TITLE
Bug in the neighborhood module

### ISSUE THREAD

**Issue by devendragovil** [pyt-team/TopoEmbedX#23]
# What
There is a bug in this part of the neighborhood_from_complex method of the neighborhood module:
<img width="815" alt="image" src="https://github.com/pyt-team/TopoEmbedX/assets/39613474/97df4b31-e611-41cb-bb97-220c893bcd9c">

Both the cases for neighborhood_type lead to an error because the ranks (rank and via_rank) are incorrect.

**Comment by mhajij** [comment]
@devendragovil can you check in the main branch now solve the problem ?

**Comment by mhajij** [comment]
@devendragovil I think I addressed that? can you please doublecheck and close the issue if you think it is done.

**Comment by devendragovil** [comment]
@mhajij  Can confirm that there is no error being thrown now.
